django_project/django_project/app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
        path('',views.index,name='index'),
        path('topics/',views.topics,name='topics'),
        path('<int:topic_id>/',views.topic,name='topic'),
        path('new_topic/',views.new_topic,name='new_topic'),
        path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),
        path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),
        ]

django_project/django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.index,name='index'),
    url(r'',include(('app.urls','app'),namespace='app')),
    #url(r'',include(('app.tempaltes','templates'),namespace='templates')),
]

django_project/django_project/app/models.py
from django.db import models

# Create your models here
class Topic(models.Model):
    text=models.CharField(max_length=100)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text
class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text  = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        return self.text

django_project/django_project/app/forms.py
from django import forms
from .models import Topic
from .models import Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

django_project/django_project/app/views.py
from django.shortcuts import render
from django.http import HttpRequest
from django.urls import reverse
from .forms import TopicForm
from .models import Topic,Entry
from .forms import TopicForm,EntryForm
from django.http import HttpResponseRedirect
# Create your views here.
def index(request):
    assert isinstance(request,HttpRequest)
    return render(request,'index.html')
def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics':topics}
    return render(request,'topics.html',context)
def topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request,'topic.html',context)
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.save()
            print("topic")
            return HttpResponseRedirect(reverse('app:topics'))
    context = {'form':form}
    return render(request,'new_topic.html',context)

def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            print("entry")
            return HttpResponseRedirect(reverse('app:topic',args=[topic_id]))
    context = {'topic':topic,'form':form}
    return render(request,'new_entry.html',context)
def edit_entry(request,entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    print(request.method)
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry,data=request.POST)
        print(form.is_valid)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app:topic',args=[topic.id]))

    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'edit_entry.html',context)

django_project/django_project/app/templates/base.html
<html>
<head>
</head>
<body>
	<p>
	<h2><a herf="{% url 'app:index' %}">Welcome</a></h2>
	</p>
	{% block content %}{% endblock %}
</body>
</html>

django_project/django_project/app/templates/edit_entry.html
{% extends "base.html" %}

{% block content %}

<p><a href="{% url 'app:topic' topic.id %}"> {{ topic }}</a><p>
<p>Edit entry</p>

<form action="{% url 'app:edit_entry' entry.id %}" method='
post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">save changes</button>
	
</form>


{% endblock content %}

django_project/django_project/app/templates/index.html
<!DOCTYPE html> 
<html> 
 
<head>  
</head> 
 
<body> 
	{% extends "base.html" %}
	{% block content %}
	<a href="/admin"><button>login</button></a>
	{% endblock content %}
</body> 
 
</html>

django_project/django_project/app/templates/new_entry.html
<html>


<head>
</head>

<body>
	{% extends "base.html" %}

	{% block content %}
	<p><a href="{% url 'app:topic' topic.id %}"> {{ topic }} </a></p>
	<p>Add a new entry</p>
	<form action="{% url 'app:new_entry' topic.id %}" method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>add entry</button>
	</form>

	{% endblock content %}
</body>





</html>

django_project/django_project/app/templates/new_topic.html
<html>

<head>
</head>
<body>
{% extends "base.html" %}

{% block content %}
<p>Add a new topic</p>

<form action="{% url 'app:new_topic' %}" method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">add topic</button>


</form>

{% endblock content %}
</body>
</html>

django_project/django_project/app/templates/topic.html
<html>
<head>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<p>Topic : {{topic}}</p>
<p>Entries:</p>
<ul>
	<a href="{% url 'app:new_entry' topic.id %}">add new entry</a>
{% for entry in entries %}
<li>
	<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
	<p>{{ entry.text|linebreaks }}</p>
	<p>
	<a href="{% url 'app:edit_entry' entry.id %}">edit entry</a>
	</p>
</li>
{% empty %}
<li>
	There are no entries for this topic yet
</li>
{% endfor %}
</ul>
{% endblock content %}
</body>
</html>

django_project/django_project/app/templates/topics.html
<html>

{% extends "base.html" %}


{% block content %}
<p>Topics</p>

<ul>
{% for topic in topics %}
	<li>
		<a href="{% url 'app:topic' topic.id %}"> {{ topic }}</a>
	</li>

	{% empty %}
	<li> No topics have been added yet,</li>
	{% endfor %}
</ul>

<a href="{% url 'app:new_topic' %}">Add new topic</a>


{% endblock content %}

</html>